In [1]:
import numpy as np

In [8]:
p=int(input("Enter number of vectors: "))
n=int(input("Enter the size of each vetcor: "))

patterns=[]

for i in range(p):
    print(f"\nEnter vectors {i+1} elements (1 or -1): ")
    vec = np.array(list(map(int,input().split())))
    patterns.append(vec)

Enter number of vectors:  4
Enter the size of each vetcor:  4



Enter vectors 1 elements (1 or -1): 


 1 -1 1 -1



Enter vectors 2 elements (1 or -1): 


 -1 1 -1 1



Enter vectors 3 elements (1 or -1): 


 1 1 -1 -1



Enter vectors 4 elements (1 or -1): 


 -1 -1 1 1


In [12]:
w=np.zeros((n,n)) 
# Training Hopfield Network
for vec in patterns:
    w+= np.outer(vec,vec)
np.fill_diagonal(w,0)   #Remove self-connections
print("\nWeight Matrix:\n")
print(w)


Weight Matrix:

[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [13]:
# Testing
print("\nEnter test vector: ")
test=np.array(list(map(int,input().split())))
print("\nTest Vector: ")
print(test)

#Recall process
result=np.dot(w,test)
result=np.where(result>=0,1,-1)
print("\nRecovered Vector:")
print(result)


Enter test vector: 


 1 -1 1 -1



Test Vector: 
[ 1 -1  1 -1]

Recovered Vector:
[ 1 -1  1 -1]
